apiVersion: apps/v1
kind: Deployment

metadata:
  name: elasticsearch-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.4.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
      
          env:
            - name: xpack.security.enabled
              value: "false"

            - name: discovery.type
              value: "single-node"

            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"