apiVersion: apps/v1
kind: Deployment

metadata:
  name: central-station-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      os: { name: linux }
      nodeSelector:
        kubernetes.io/os: linux
      containers:
          - name: central-station
            image: mustafafarrag/central-station:latest
            imagePullPolicy: Never
            ports:
              - containerPort: 7777
            env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            
            - name: PARQUET_PATH
              value: "/home/parquet"

            - name: ELASTIC_SERVICE
              value: "elasticsearch-service"

            - name: ELASTIC_PORT
              value: "9200"

            - name: BITCASK_PATH
              value: "/mnt/bitcask"

            - name: BITCASK_MERGE_DELAY
              value: "600000"

            volumeMounts:
            - mountPath: "/home/parquet"
              name: parquet-mount
            - mountPath: "/mnt/bitcask"
              name: bitcask-mount

      volumes:
      - name: parquet-mount
        persistentVolumeClaim:
          claimName: parquet-pvc
      - name: bitcask-mount
        persistentVolumeClaim:
          claimName: bitcask-pvc