FROM eclipse-temurin:21-jdk-jammy

COPY target/ /usr/src/app/

WORKDIR /usr/src/app

EXPOSE 6666

ENV KAFKA_BOOTSTRAP=kafka-service:9092
ENV STATION_ID=1
ENV LOCATION="Cairo, Egypt"
ENV LATITUDE=30.0626
ENV LONGITUDE=31.2497

ENTRYPOINT java -jar Weather_Station-1.0-SNAPSHOT.jar