
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-9
  template:
    metadata:
      labels:
        app: weather-station-9
    spec:
      containers:
        - name: weather-station-9
          image: mustafafarrag/weather-station:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "9"
            - name: LOCATION
              value: "Stockholm, Sweden"
            - name: LATITUDE
              value: "59.3294"
            - name: LONGITUDE
              value: "18.0687"
