
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-8-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-8
  template:
    metadata:
      labels:
        app: weather-station-8
    spec:
      containers:
        - name: weather-station-8
          image: mustafafarrag/weather-station:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "8"
            - name: LOCATION
              value: "California, USA"
            - name: LATITUDE
              value: "38.6275"
            - name: LONGITUDE
              value: "-92.5666"
