
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-7-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-7
  template:
    metadata:
      labels:
        app: weather-station-7
    spec:
      containers:
        - name: weather-station-7
          image: mustafafarrag/weather-station:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "7"
            - name: LOCATION
              value: "Washington D.C, USA"
            - name: LATITUDE
              value: "38.8951"
            - name: LONGITUDE
              value: "-77.0364"
