
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-2
  template:
    metadata:
      labels:
        app: weather-station-2
    spec:
      containers:
        - name: weather-station-2
          image: mustafafarrag/weather-station:latest
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "2"
            - name: LOCATION
              value: "Riyadh, Saudi Arabia"
            - name: LATITUDE
              value: "24.6877"
            - name: LONGITUDE
              value: "46.7219"
