
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-1
  template:
    metadata:
      labels:
        app: weather-station-1
    spec:
      containers:
        - name: weather-station-1
          image: mustafafarrag/weather-station:latest
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "1"
            - name: LOCATION
              value: "Cairo, Egypt"
            - name: LATITUDE
              value: "30.0626"
            - name: LONGITUDE
              value: "31.2497"
