
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-3
  template:
    metadata:
      labels:
        app: weather-station-3
    spec:
      containers:
        - name: weather-station-3
          image: mustafafarrag/weather-station:latest
          ports:
            - containerPort: 6666
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: STATION_ID
              value: "3"
            - name: LOCATION
              value: "Cap Town, South Africa"
            - name: LATITUDE
              value: "-33.9258"
            - name: LONGITUDE
              value: "18.4232"
